# Included files are defined in Rakefile

# NB All Rubocop linters MUST be defined in rubocop.yml, NOT here. (will not work)

linters:
  LineLength:
    max: 120

  RuboCop:
    # These cops are incredibly noisy since the Ruby we extract from Slim
    # templates isn't well-formatted, so we ignore them.
    # WARNING: If you define this list in your own .slim-lint.yml file, you'll
    # be overriding the list defined here.
    ignored_cops:
    - Layout/LineLength
    - Layout/ArgumentAlignment
    - Layout/ArrayAlignment
    - Layout/HashAlignment
    - Layout/ParameterAlignment
    - Layout/EmptyLineAfterGuardClause
    - Layout/FirstParameterIndentation
    - Layout/IndentArray
    - Layout/IndentationConsistency
    - Layout/IndentationWidth
    - Layout/FirstArgumentIndentation
    - Layout/FirstHashElementIndentation
    - Layout/InitialIndentation
    - Layout/MultilineArrayBraceLayout
    - Layout/MultilineAssignmentLayout
    - Layout/MultilineHashBraceLayout
    - Layout/MultilineMethodCallBraceLayout
    - Layout/MultilineMethodCallIndentation
    - Layout/MultilineMethodDefinitionBraceLayout
    - Layout/MultilineOperationIndentation
    - Layout/TrailingEmptyLines
    - Layout/TrailingWhitespace
    - Lint/BlockAlignment
    - Lint/EndAlignment
    - Lint/Void
    - Metrics/BlockLength
    - Metrics/BlockNesting
    - Naming/FileName
    - Style/FrozenStringLiteralComment
    - Style/IfUnlessModifier
    - Style/Next
    - Style/WhileUntilModifier
    - Style/SymbolProc
    # Our own ignores
    - Style/LambdaCall
    - Layout/IndentHash
    - Rails/OutputSafety
    - Style/IdenticalConditionalBranches
    - Style/WordArray
